import { Inter } from "next/font/google";
import "./globals.css";
import NavbarA from "@/components/NavbarA";
import NavbarB from "@/components/NavbarB";
const inter = Inter({ subsets: ["latin"] });
import bg from "../../public/images/background.png"
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-zinc-600`}>
        {/* <NavbarA/> */}
        <NavbarB/>
        {/* {children} */}
      </body>
    </html>
  );
}
